name: Publish TypeScript Client Library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: | 
            npm install -g @typespec/compiler
            tsp install

      - name: Compile TypeSpec
        run: tsp compile .

      - name: Generate OpenAPI client library
        run: make generate-all-clients

      - name: Publish Typescript client library
        run: |
          cd bin
          npm install
          npm run build
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Go client library
        run: |
          cd bin/go-client
          go mod tidy
          go build
          git config --global init.defaultBranch master
          git config --global user.email "pfreitas1@gmail.com"
          git config --global user.name "Paulo Freitas"
          git init
          git branch -m master
          git remote add origin https://pffreitas:${{secrets.GH_GO_CLIENT_REPO_PAT}}@github.com/pffreitas/cosmic-dolphin-api-go.git
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git tag v$(date +'%Y%m%d%H%M%S')
          git pull origin master
          git push --force origin master 2>&1 | grep -v 'To https'
          git push origin --tags
          
        env:
          GIT_TOKEN: ${{ secrets.GH_GO_CLIENT_REPO_PAT }}
